### ISSUE TITLE
13.2.7.1 Long Running Operations.

### ISSUE THREAD

**Issue by edent** [Microsoft/api-guidelines#52] opened 2016-07-25 09:03 UTC
In [13.2.7.1](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#132-stepwise-long-running-operations), the user is told to POST to one URl and then poll another URl to see whether the operation has completed.

The initial URl uses [202](https://tools.ietf.org/html/rfc7231#section-6.3.3) to indicate that the request has been received. The subsequent URl responds with

> Server responds that results are still not ready and optionally provides a recommendation to wait 30 seconds.

```
HTTP/1.1 200 OK
Retry-After: 30
```

I would understand `200` to mean that the request was accepted and completed.

Would it make more sense to use a code like [102 Processing](https://tools.ietf.org/html/rfc2518#section-10.1)?

> The 102 (Processing) status code is an interim response used to
   inform the client that the server has accepted the complete request,
   but has not yet completed it.  This status code SHOULD only be sent
   when the server has a reasonable expectation that the request will
   take significant time to complete. As guidance, if a method is taking
   longer than 20 seconds (a reasonable, but arbitrary value) to process
   the server SHOULD return a 102 (Processing) response. The server MUST
   send a final response after the request has been completed.

Or, perhaps, continue sending `202` until the request is completed.

**Comment by garethj-msft** [comment] 2016-07-26 06:47
My understanding is that 102 is a code that should be sent as an interim for a single response, whereas the polling response has completed successfully, so 200 is more correct.  Our position in general is that the HTTP status code refers to the specific HTTP call rather than the overarching operation.

**Comment by darrelmiller** [comment] 2016-07-26 12:55
@edent The 200 response refers to the client making a GET request on a status resource.  That [status/progress resource](https://gooroo.io/GoorooTHINK/Article/16673/Http-Patterns-Progress/21560#.V5ddeYVFzmQ) is retrieved successfully and so the 200 is appropriate.  How the progress resource reports the state of the operation is not defined by HTTP, but in the pattern doc I linked to I make some suggestions.

**Comment by garethj-msft** [comment] 2016-08-01 05:04
I think we're comfortable with the current use of the codes here, so 'm going to close this one.

**Closed by garethj-msft** 2016-08-01 05:04 UTC

**Comment by whozDougie** [comment] 2016-11-18 14:41
Hi there, 

I started following the guidelines on 200 with a Retry-After, however, I quickly found that other frameworks such as jQuery does not support 200 with a Retry-After. An Article from Mozilla indicates that Retry-After is used with "413 Payload Too Large" and "503 Service Unavailable".
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Also another article states the header can be used with 503 or 3XX: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html 

The problem is I then have to manually write code on these frameworks which have followed "standards" for the implementation. For example, if I try and get a Retry-After from a $.ajax call and I try to get headers, by default it jQuery will ignore the Retry-After header!

I'm not sure which standard / guideline is correct here, but I don't feel very confident with using 200 - unless I am missing something here. 

Many thanks,
WhozDougie
